CREATE TABLE "countries" (
	"code" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"locale" text NOT NULL,
	"language" text NOT NULL,
	"timezone" text NOT NULL,
	"currency" text NOT NULL,
	"currency_symbol" text NOT NULL,
	"phone_code" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cities" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"country_code" text NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "cities_country_name_unique" ON "cities" ("country_code", "name");
--> statement-breakpoint
ALTER TABLE "cities" ADD CONSTRAINT "cities_country_code_countries_code_fk" FOREIGN KEY ("country_code") REFERENCES "public"."countries"("code") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
INSERT INTO "countries" ("code", "name", "locale", "language", "timezone", "currency", "currency_symbol", "phone_code") VALUES
('CO', 'Colombia', 'es-CO', 'es', 'America/Bogota', 'COP', '$', '+57'),
('MX', 'Mexico', 'es-MX', 'es', 'America/Mexico_City', 'MXN', '$', '+52'),
('AR', 'Argentina', 'es-AR', 'es', 'America/Argentina/Buenos_Aires', 'ARS', '$', '+54'),
('BR', 'Brasil', 'pt-BR', 'pt', 'America/Sao_Paulo', 'BRL', 'R$', '+55'),
('CL', 'Chile', 'es-CL', 'es', 'America/Santiago', 'CLP', '$', '+56'),
('PE', 'Peru', 'es-PE', 'es', 'America/Lima', 'PEN', 'S/', '+51'),
('EC', 'Ecuador', 'es-EC', 'es', 'America/Guayaquil', 'USD', '$', '+593'),
('VE', 'Venezuela', 'es-VE', 'es', 'America/Caracas', 'USD', '$', '+58'),
('UY', 'Uruguay', 'es-UY', 'es', 'America/Montevideo', 'UYU', '$U', '+598'),
('PY', 'Paraguay', 'es-PY', 'es', 'America/Asuncion', 'PYG', 'G', '+595'),
('BO', 'Bolivia', 'es-BO', 'es', 'America/La_Paz', 'BOB', 'Bs', '+591'),
('PA', 'Panama', 'es-PA', 'es', 'America/Panama', 'USD', '$', '+507'),
('CR', 'Costa Rica', 'es-CR', 'es', 'America/Costa_Rica', 'CRC', 'C', '+506'),
('DO', 'Republica Dominicana', 'es-DO', 'es', 'America/Santo_Domingo', 'DOP', 'RD$', '+1-809'),
('GT', 'Guatemala', 'es-GT', 'es', 'America/Guatemala', 'GTQ', 'Q', '+502'),
('HN', 'Honduras', 'es-HN', 'es', 'America/Tegucigalpa', 'HNL', 'L', '+504'),
('SV', 'El Salvador', 'es-SV', 'es', 'America/El_Salvador', 'USD', '$', '+503'),
('NI', 'Nicaragua', 'es-NI', 'es', 'America/Managua', 'NIO', 'C$', '+505'),
('CU', 'Cuba', 'es-CU', 'es', 'America/Havana', 'CUP', '$', '+53'),
('PR', 'Puerto Rico', 'es-PR', 'es', 'America/Puerto_Rico', 'USD', '$', '+1-787')
ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO "cities" ("country_code", "name") VALUES
('CO', 'Bogota'),
('CO', 'Medellin'),
('CO', 'Cali'),
('CO', 'Barranquilla'),
('CO', 'Bucaramanga'),
('MX', 'Ciudad de Mexico'),
('MX', 'Guadalajara'),
('MX', 'Monterrey'),
('MX', 'Puebla'),
('MX', 'Tijuana'),
('AR', 'Buenos Aires'),
('AR', 'Cordoba'),
('AR', 'Rosario'),
('AR', 'Mendoza'),
('AR', 'La Plata'),
('BR', 'Sao Paulo'),
('BR', 'Rio de Janeiro'),
('BR', 'Brasilia'),
('BR', 'Salvador'),
('BR', 'Fortaleza'),
('CL', 'Santiago'),
('CL', 'Valparaiso'),
('CL', 'Concepcion'),
('CL', 'La Serena'),
('CL', 'Antofagasta'),
('PE', 'Lima'),
('PE', 'Arequipa'),
('PE', 'Trujillo'),
('PE', 'Chiclayo'),
('PE', 'Piura'),
('EC', 'Quito'),
('EC', 'Guayaquil'),
('EC', 'Cuenca'),
('EC', 'Manta'),
('EC', 'Ambato'),
('VE', 'Caracas'),
('VE', 'Maracaibo'),
('VE', 'Valencia'),
('VE', 'Barquisimeto'),
('VE', 'Maracay'),
('UY', 'Montevideo'),
('UY', 'Salto'),
('UY', 'Paysandu'),
('UY', 'Las Piedras'),
('UY', 'Rivera'),
('PY', 'Asuncion'),
('PY', 'Ciudad del Este'),
('PY', 'San Lorenzo'),
('PY', 'Luque'),
('PY', 'Encarnacion'),
('BO', 'La Paz'),
('BO', 'Santa Cruz'),
('BO', 'Cochabamba'),
('BO', 'Oruro'),
('BO', 'Sucre'),
('PA', 'Ciudad de Panama'),
('PA', 'San Miguelito'),
('PA', 'Colon'),
('PA', 'David'),
('PA', 'La Chorrera'),
('CR', 'San Jose'),
('CR', 'Alajuela'),
('CR', 'Cartago'),
('CR', 'Heredia'),
('CR', 'Puntarenas'),
('DO', 'Santo Domingo'),
('DO', 'Santiago'),
('DO', 'La Vega'),
('DO', 'San Pedro'),
('DO', 'San Cristobal'),
('GT', 'Ciudad de Guatemala'),
('GT', 'Mixco'),
('GT', 'Villa Nueva'),
('GT', 'Quetzaltenango'),
('GT', 'Escuintla'),
('HN', 'Tegucigalpa'),
('HN', 'San Pedro Sula'),
('HN', 'La Ceiba'),
('HN', 'Choloma'),
('HN', 'Comayagua'),
('SV', 'San Salvador'),
('SV', 'Santa Ana'),
('SV', 'San Miguel'),
('SV', 'Soyapango'),
('SV', 'Mejicanos'),
('NI', 'Managua'),
('NI', 'Leon'),
('NI', 'Masaya'),
('NI', 'Chinandega'),
('NI', 'Granada'),
('CU', 'La Habana'),
('CU', 'Santiago de Cuba'),
('CU', 'Camaguey'),
('CU', 'Holguin'),
('CU', 'Santa Clara'),
('PR', 'San Juan'),
('PR', 'Bayamon'),
('PR', 'Carolina'),
('PR', 'Ponce'),
('PR', 'Caguas')
ON CONFLICT DO NOTHING;
